### ISSUE TITLE
Problem with "versionConfigPath" variable

### ISSUE THREAD

**Issue by lol1kn1ght** [morozow/versionings#29]
config.js
```javascript
const versionConfigPath = path.join(process.env.PWD, 'version.json');
```
That's doesn't work

I'm locally fixed that by 

config.js
```javascript
const versionConfigPath = path.join(process.cwd(), "version.json");
```

**Comment by morozow** [comment]
Hey @lol1kn1ght, thanks for the advise. This variable has been provided for the cross platform maintenance with the problem you've met. The pull request is approved and valid for the next version now. The second commit `adef542724f55f8352f8ca36a2d0ae056ef2bc0c` has the invalid state regarding the approved codestyle.
